"""config.py — Objeto de configuração central do pipeline (dataclass Config).

Extraído de pipeline.py (item 10 da auditoria) para isolar o schema de
configuração da lógica de execução. É uma dataclass PURA (só campos com
defaults, sem métodos e sem dependência de pipeline/numpy/sklearn), então
pode ser importada por qualquer módulo sem risco de import circular.

pipeline.py reexporta `Config`, então `pipeline.Config` e
`from pipeline import Config` continuam funcionando sem alteração.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

__all__ = [
    "__version__",
    "NOME_GRAFICOS",
    "NOME_TABELAS",
    "NOME_RELATORIOS",
    "NOME_MODELOS",
    "Config",
]

# Versão canônica do pacote. Mora aqui (módulo sem dependências) para ser
# importável por qualquer módulo — pipeline.py e guaraci/__init__.py a
# reexportam, então `pipeline.__version__` e `from guaraci import __version__`
# seguem funcionando. Fonte ÚNICA: nunca duplicar um literal "vXX.Y".
__version__ = "31.9.0"

# Nome amigavel de cada nivel de analise (valor interno N1/N2/N3 inalterado).
_NIVEL_NOME = {
    "N1": "Classificacao por especie",
    "N2": "Discriminacao puro/adulterado",
    "N3": "Quantificacao de teor",
}

# Slug curto p/ NOME DE PASTA de saida (auditoria de 2026-07-12, P8 residual:
# o nome de pasta ainda expunha N1/N2/N3 cru, ex. PLSDA_OE_N2_..., mesmo com
# os menus ja mostrando o nome amigavel). cfg.level continua sendo "N1"/"N2"/
# "N3" internamente -- so' o SLUG usado no nome do diretorio muda; nao afeta
# nenhuma logica de negocio, so' o texto do caminho gravado em disco.
_NIVEL_SLUG_PASTA = {
    "N1": "PorEspecie",
    "N2": "Autenticacao",
    "N3": "Quantificacao",
}

# Nomes de subpasta da saida de cada execucao (auditoria jul/2026, item 4:
# reestruturacao Amostra/Modo/{Graficos,Tabelas,Relatorios}). Fonte UNICA —
# writers (pipeline.py/figuras.py/avaliacao_modelos.py/selecao_variaveis.py)
# e readers (reports.py/app_logic.py/app_tabs/) importam daqui, nunca com a
# string literal, para que um rename futuro seja de 1 lugar so.
NOME_GRAFICOS   = "Graficos"     # antigo "figuras"
NOME_TABELAS    = "Tabelas"      # antigo "dados"
NOME_RELATORIOS = "Relatorios"   # antigo "logs"
NOME_MODELOS    = "Modelos"      # antigo "modelos" (so' capitalizacao)


@dataclass
class Config:
    mode: str = "dx"                          # "dx" | "csv" | "imagem" | "sintetico"

    # ---- INPUT ----
    # Root folder with subfolders per species (each subfolder = 1 class) OR
    # single folder with .dx files (legacy mode). Auto-detected.
    # DO NOT version personal paths: the real path goes in config.yaml
    # (gitignored). This default is just a portable example.
    input_folder: str = r"dados"
    class_part: int = 0                     # fallback if no subfolders
    extract_conc_from_filename: bool = True        # only used in old fallback
    csv_file: str = "seus_espectros.csv"
    class_column: str = "classe"
    conc_column: Optional[str] = None
    use_parse_title: bool = True             # uses ##TITLE= from JCAMP-DX
    # mode="imagem" (colorimetria digital, prototipo): extrai estatisticas de
    # cor (RGB/HSV/Lab) de cada imagem, reaproveitando input_folder (mesma
    # convencao de 1 subpasta por classe do mode dx). Use preprocessamento_
    # padrao="autoscaling" (NAO "msc_sg_mc"/"snv_sg_mc" — SG exige janela <=
    # n_variaveis e MSC/SG pressupoem sinal espectral continuo, sem sentido
    # p/ um vetor curto de estatisticas de cor) e ajuste wn_min/wn_max p/
    # cobrir o eixo simbolico 0..n_features-1 (ver dados_imagem.py).
    image_crop: Tuple[float, float, float, float] = (0.0, 0.0, 1.0, 1.0)
    include_image_texture: bool = False       # GLCM — requer scikit-image

    # ---- OUTPUT (auto-generated by generate_output_name) ----
    output_root_folder: str = "resultados_tcc"
    level: str = "N1"                         # "N1" | "N2" | "N3"
    # Objetivo cientifico do run — controla QUAIS figuras/relatorios sao
    # gerados (ver modos_analise.py). "auto" (default) deriva do nivel
    # preservando o comportamento historico (N1/N2 -> classificacao,
    # N3 -> quantificacao). Valores explicitos: "exploratorio" |
    # "classificacao" | "quantificacao" sobrepoem a derivacao. O Modo
    # Exploratorio gera apenas PCA/HCA/loadings/pre-proc (sem PLS-DA).
    objective: str = "auto"                    # "auto" | "exploratorio" | "classificacao" | "quantificacao"
    tag:   str = ""                            # free label e.g. "pure", "soybean"
    output_folder: str = ""                     # DO NOT edit manually
    # Confianca do agrupamento group-aware desta execucao -- "high" (mae_id
    # real, ex.: .dx/sintetico), "medium" (associacao manual via CSV, modo
    # imagem), "none" (sem fonte de agrupamento, fallback StratifiedKFold).
    # DO NOT edit manually -- escrito por dados_io._leitor_imagem apos
    # detectar a estrutura de dados; default "high" cobre todo mode que
    # nao sobrescreve isto (dx/sintetico ja' tem mae_id real por natureza).
    grouping_guarantee: str = "high"
    output_format: str = "png"                # png | pdf | svg
    save_dpi: int = 600
    show_plots: bool = False

    # ---- Score plot style (PCA / PLS-DA / OPLS) ----
    # Disable for "clean" scatter (color by class only, no shapes/contours).
    show_class_markers: bool = False   # False -> all circles 'o'
    show_group_ellipses:     bool = False   # False -> no T2/convex hull ellipse

    # ---- Figure detail level ----
    # False (default): gera apenas o conjunto ESSENCIAL de figuras (scores PCA/
    #   PLS-DA, confusao, ROC/AUC, selecao de LVs, SR+VIP, outliers T2/Q, e a
    #   aceitacao DD-SIMCA quando aplicavel). Mais rapido e menos arquivos.
    # True: gera tambem as figuras EXPLORATORIAS/detalhadas (HCA, loadings PCA,
    #   pre-processamento, contribuicao de score, DD-SIMCA por classe, Cooman).
    detailed_figures: bool = False

    # ---- Group-aware validation (Q1 differentiator) ----
    # When True and mae_id is available, uses GroupKFold/GroupShuffleSplit
    # so that T1/T2/T3 of the same physical point stay in the same fold/holdout.
    group_by_mae_id: bool = True

    # ---- Perfil da matriz ------------------------------------------------
    # Junta num so' lugar tudo que e' propriedade da MATRIZ (faixa do eixo,
    # pre-processamento padrao, unidade, vocabulario da saida) -- ver
    # `guaraci/perfis_matriz/*.yaml` e `perfil_matriz.py`. Trocar de matriz
    # e' trocar este nome, nunca editar codigo-fonte. Aceita tambem o
    # caminho de um YAML proprio. Nome desconhecido levanta erro com a
    # lista do que existe, em vez de cair num padrao errado em silencio.
    matrix_profile: str = "generico"

    # ---- Modo de rotulo na QUANTIFICACAO ---------------------------------
    # "cego" (PADRAO): a calibracao por classe usa a classe PREDITA pelo
    #     classificador, nao a verdadeira. E' o unico mode que corresponde
    #     ao uso real -- quem manda uma amostra desconhecida nao sabe a
    #     classe dela, entao um R2 obtido com a classe verdadeira mede algo
    #     que o usuario nunca tera' em maos.
    # "controle": usa a classe verdadeira. Valido apenas para diagnostico
    #     interno (isolar erro de quantificacao do erro de classificacao).
    #     Numeros obtidos assim NAO representam o desempenho de uso.
    label_mode: str = "cego"

    # ---- Spectral truncation ---------------------------------------------
    # Padrao herdado do caso de uso de origem (FT-NIR difuso, 4000-10000
    # cm-1: remove ruido de borda de FFT, onde a derivada SG cria VIP
    # falso). Um perfil de matriz sobrescreve estes valores quando eles
    # estao no default. Aplicado ANTES de qualquer pre-processamento.
    wn_min: float = 4000.0
    wn_max: float = 10000.0

    # ---- Preprocessing ---------------------------------------------------
    # Quick preset. When != 'custom', overrides individual flags.
    #   'msc_sg_mc'   : MSC -> SG -> mean-centering (padrao: FT-NIR difuso
    #                   com espalhamento forte; ver comparar_pre_processamentos)
    #   'snv_sg_mc'   : SNV -> SG -> mean-centering (Rinnan et al.)
    #   'autoscaling' : StandardScaler only (good on subset, poor on full: 0.472)
    #   'mc'          : mean-centering only
    #   'custom'      : honors apply_snv / apply_sg / apply_mc below
    default_preprocessing: str = "msc_sg_mc"   # FT-NIR difuso c/ espalhamento

    apply_snv: bool = True
    apply_sg: bool = True
    sg_window: int = 25
    sg_polyorder: int = 2
    sg_deriv: int = 1
    apply_mc: bool = True

    max_lvs: int = 40
    n_pcs_pca: int = 10
    # HCA: dendrogram uses PCA scores with hca_n_pcs components
    # (reduces spectral noise before clustering). compare_hca_pipelines
    # generates a dendrogram panel per preprocessing method.
    hca_n_pcs: int = 65
    # Extra opt-in (fora do conjunto padrao de ~7 figuras "core"; ligar na mao).
    compare_hca_pipelines: bool = False
    n_splits_cv: int = 5
    n_repeats_cv: int = 3

    frac_cal: float = 0.70
    # Metodo de split calibracao/validacao da regressao PLS (N2/N3):
    # 'aleatoria' (default, comportamento historico -- GroupShuffleSplit
    # group-aware por mae_id, ou permutacao simples sem mae_id) |
    # 'kennard_stone' (Kennard & Stone 1969 -- cobertura maximamente
    # representativa do espaco espectral em vez de aleatoria; group-aware,
    # colapsa replicas fisicas num espectro medio por grupo antes de
    # selecionar). Hiperparametro avancado, config-only (mesmo precedente
    # de ipls_n_intervalos/vip_threshold_sel/etc -- nao exposto no app/CLI).
    cal_val_split: str = "aleatoria"   # 'aleatoria' | 'kennard_stone'

    n_permutations: int = 200
    n_permutations_wold: int = 200        # 200 for publication; 50 is minimum for diagnostic
    n_bootstrap_vip: int = 30
    n_bootstrap_bca: int = 500
    # Os 3 abaixo sao "extra" opt-in (fora do conjunto padrao de ~7 figuras
    # "core"): validacoes/comparacoes adicionais, uteis mas nao essenciais
    # para o resultado principal. Ligar na mao quando quiser mais rigor.
    comparar_pipelines: bool = False
    run_wold: bool = False
    run_cv_anova: bool = False
    # Teste de incerteza de Martens (Martens & Martens 2000): jackknifing
    # group-aware dos coeficientes PLS -- teste de hipotese formal (p-valor)
    # de significancia por variavel, mais rigoroso que VIP/SR (magnitude).
    run_martens: bool = False
    # Paralelismo (processos, via joblib/loky) para os testes de permutacao/
    # Wold — cada iteracao e independente (mesma X, so o rotulo e
    # reembaralhado), entao rodar em paralelo NAO altera nenhum resultado
    # numerico, so o tempo de execucao (verificado por teste de regressao).
    # Padrao 1 (sequencial) preserva o comportamento atual sem mudanca.
    # Medido: n_jobs=4 ~2x mais rapido no pipeline completo (threading NAO
    # ajuda aqui — overhead do sklearn e Python/GIL-bound; processos sim).
    # Em ambientes com pouca RAM/CPU (ex.: Streamlit Cloud gratuito), deixe em 1
    # (processos extras multiplicam o uso de memoria).
    n_jobs_permutation: int = 1

    frac_holdout: float = 0.20         # v14: external holdout by default
    # v15: pure samples (conc==0) ALWAYS stay in training — they are scarce (3/class)
    # and precious for DD-SIMCA/interpretation. Only adulterated go to holdout.
    holdout_preserves_pure: bool = True
    seed_holdout: int = 42

    n_per_class: int = 20
    n_synthetic_points: int = 1000
    n_synthetic_replicates: int = 3   # replicas fisicas/ponto (estilo T1/T2/T3) no mode sintetico
    # Modo sintetico: adulterantes a gerar por especie (letras A/M/S). Vazio =
    # so o gradiente puro legado (nao muda dados de teste existentes). Quando
    # preenchido, cada especie ganha puros + esses adulterantes em varios teores
    # -> permite exercitar o heatmap especie x adulterante (N3) sinteticamente.
    synthetic_adulterants: Tuple[str, ...] = ()

    seed: int = 42

    # Sprint 3
    # DD-SIMCA e' o "core" automatico de N2 (executar() forca True quando
    # level=="N2", e ignora o toggle quando level=="N1" -- ver executar()).
    # Default False aqui so' afeta N3, onde vira extra opt-in de verdade.
    run_ddsimca: bool = False
    ddsimca_n_components: int = 7       # PCA LVs per DD-SIMCA model (3 was insufficient — UCL poorly calibrated)
    ddsimca_ucl_method: str = "empirical"  # 'empirical' | 'theoretical' | 'chi2'
    # v14: 'todos' trains each model with ALL samples of the class
    # (exploratory; works with few pure samples). 'puros' = true one-class N2
    # but requires >=15 pure/class (current data: 3/class).
    ddsimca_train_on: str = "puros"   # 'todos' | 'puros'
    # Diagnostico complementar ao LOGO via Procrustes Cross-Validation
    # (Kucheryavskiy/Rodionova/Pomerantsev) -- exige o extra opcional
    # [robusto] (pacote 'prcv'). NUNCA substitui o aviso "nao validado" do
    # LOGO quando ha' so' 1 grupo de replica -- ver
    # classificadores.ddsimca_pcv_sensitivity().
    ddsimca_pcv: bool = False
    # Extra opt-in (fora do conjunto padrao de ~7 figuras "core").
    run_opls: bool = False
    n_ortho_opls: int = 1               # OPLS-DA orthogonal components
    run_benchmark: bool = False    # v27: SVM / RF / XGBoost vs PLS-DA (same CV)
    # Auto-Benchmark de REGRESSAO (N2/N3): Ridge/Lasso/Elastic Net/SVR/RF vs
    # PLS-R, por especie, mesmo split cal/val e pre-processamento (ver
    # avaliacao_modelos.benchmark_regression_by_species). So' roda quando
    # ha regressao multi-especie (mesma condicao de pls_regression_by_species).
    run_benchmark_regression: bool = False
    run_monte_carlo: bool = False      # v28: MC CV (N × GroupShuffleSplit) for 95% CI
    n_monte_carlo: int = 100               # number of MC repetitions
    monte_carlo_test_size: float = 0.25    # test fraction per MC repetition
    monte_carlo_include_all: bool = False # v28: run all benchmark models in MC CV
    run_shap: bool = False            # v28: SHAP values (TreeExplainer) for ensemble
    shap_max_samples: int = 500        # sample limit for SHAP (memory control)

    # ---- Class exclusion (e.g. Copaiba with anomalous batch) ----
    exclude_classes: Tuple[str, ...] = ()

    # ---- STAGE 4: Variable selection ----
    # Extra opt-in (fora do conjunto padrao de ~7 figuras "core").
    executar_etapa4: bool = False
    ipls_n_intervalos: int = 20         # iPLS: number of intervals
    vip_threshold_sel: float = 1.0      # selection by VIP >= threshold
    sr_top_frac: float = 0.20           # selection by SR: top fraction
    splsda_keep_by_comp: int = 50      # sPLS-DA: non-zero variables/component
    # SPA/APS (Successive Projections Algorithm, Araujo et al. 2001) and
    # AG (Genetic Algorithm, GA-PLS) — opt-in (default False) because they
    # run many more CV evaluations than iPLS/VIP/SR/sPLS-DA (heavier, like
    # run_benchmark/run_shap).
    run_spa: bool = False
    spa_n_vars_max: int = 20            # SPA: max chain length (variables)
    spa_n_starts: int = 25              # SPA: starting variables sampled (evenly across spectrum)
    executar_ag: bool = False
    ag_tam_populacao: int = 20          # AG: chromosomes per generation
    ag_n_geracoes: int = 15             # AG: number of generations
    ag_prob_mutacao: float = 0.02       # AG: per-bit mutation probability
    ag_frac_inicial: float = 0.10       # AG: initial fraction of variables "on" per chromosome
