"""config.py — Objeto de configuração central do pipeline (dataclass Config).

Extraído de pipeline.py (item 10 da auditoria) para isolar o schema de
configuração da lógica de execução. É uma dataclass PURA (só campos com
defaults, sem métodos e sem dependência de pipeline/numpy/sklearn), então
pode ser importada por qualquer módulo sem risco de import circular.

pipeline.py reexporta `Config`, então `pipeline.Config` e
`from pipeline import Config` continuam funcionando sem alteração.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

# Versão canônica do pacote. Mora aqui (módulo sem dependências) para ser
# importável por qualquer módulo — pipeline.py e guaraci/__init__.py a
# reexportam, então `pipeline.__version__` e `from guaraci import __version__`
# seguem funcionando. Fonte ÚNICA: nunca duplicar um literal "vXX.Y".
__version__ = "31.6.0"

# Nome amigavel de cada nivel de analise (valor interno N1/N2/N3 inalterado).
_NIVEL_NOME = {
    "N1": "Classificacao por especie",
    "N2": "Discriminacao puro/adulterado",
    "N3": "Quantificacao de teor",
}

# Slug curto p/ NOME DE PASTA de saida (auditoria de 2026-07-12, P8 residual:
# o nome de pasta ainda expunha N1/N2/N3 cru, ex. PLSDA_OE_N2_..., mesmo com
# os menus ja mostrando o nome amigavel). cfg.nivel continua sendo "N1"/"N2"/
# "N3" internamente -- so' o SLUG usado no nome do diretorio muda; nao afeta
# nenhuma logica de negocio, so' o texto do caminho gravado em disco.
_NIVEL_SLUG_PASTA = {
    "N1": "PorEspecie",
    "N2": "Autenticacao",
    "N3": "Quantificacao",
}

# Nomes de subpasta da saida de cada execucao (auditoria jul/2026, item 4:
# reestruturacao Amostra/Modo/{Graficos,Tabelas,Relatorios}). Fonte UNICA —
# writers (pipeline.py/figuras.py/avaliacao_modelos.py/selecao_variaveis.py)
# e readers (reports.py/app_logic.py/app_tabs/) importam daqui, nunca com a
# string literal, para que um rename futuro seja de 1 lugar so.
NOME_GRAFICOS   = "Graficos"     # antigo "figuras"
NOME_TABELAS    = "Tabelas"      # antigo "dados"
NOME_RELATORIOS = "Relatorios"   # antigo "logs"
NOME_MODELOS    = "Modelos"      # antigo "modelos" (so' capitalizacao)


@dataclass
class Config:
    modo: str = "dx"                          # "dx" | "csv" | "imagem" | "sintetico"

    # ---- INPUT ----
    # Root folder with subfolders per species (each subfolder = 1 class) OR
    # single folder with .dx files (legacy mode). Auto-detected.
    # DO NOT version personal paths: the real path goes in config.yaml
    # (gitignored). This default is just a portable example.
    pasta_entrada: str = r"dados"
    parte_classe: int = 0                     # fallback if no subfolders
    extrair_conc_filename: bool = True        # only used in old fallback
    arquivo_csv: str = "seus_espectros.csv"
    coluna_classe: str = "classe"
    coluna_conc: Optional[str] = None
    usar_parse_title: bool = True             # uses ##TITLE= from JCAMP-DX
    # modo="imagem" (colorimetria digital, prototipo): extrai estatisticas de
    # cor (RGB/HSV/Lab) de cada imagem, reaproveitando pasta_entrada (mesma
    # convencao de 1 subpasta por classe do modo dx). Use preprocessamento_
    # padrao="autoscaling" (NAO "msc_sg_mc"/"snv_sg_mc" — SG exige janela <=
    # n_variaveis e MSC/SG pressupoem sinal espectral continuo, sem sentido
    # p/ um vetor curto de estatisticas de cor) e ajuste wn_min/wn_max p/
    # cobrir o eixo simbolico 0..n_features-1 (ver dados_imagem.py).
    imagem_recorte: Tuple[float, float, float, float] = (0.0, 0.0, 1.0, 1.0)
    imagem_incluir_textura: bool = False       # GLCM — requer scikit-image

    # ---- OUTPUT (auto-generated by gerar_nome_saida) ----
    pasta_saida_raiz: str = "resultados_tcc"
    nivel: str = "N1"                         # "N1" | "N2" | "N3"
    # Objetivo cientifico do run — controla QUAIS figuras/relatorios sao
    # gerados (ver modos_analise.py). "auto" (default) deriva do nivel
    # preservando o comportamento historico (N1/N2 -> classificacao,
    # N3 -> quantificacao). Valores explicitos: "exploratorio" |
    # "classificacao" | "quantificacao" sobrepoem a derivacao. O Modo
    # Exploratorio gera apenas PCA/HCA/loadings/pre-proc (sem PLS-DA).
    objetivo: str = "auto"                    # "auto" | "exploratorio" | "classificacao" | "quantificacao"
    tag:   str = ""                            # free label e.g. "pure", "soybean"
    pasta_saida: str = ""                     # DO NOT edit manually
    formato_saida: str = "png"                # png | pdf | svg
    dpi_salvar: int = 600
    mostrar_graficos: bool = False

    # ---- Score plot style (PCA / PLS-DA / OPLS) ----
    # Disable for "clean" scatter (color by class only, no shapes/contours).
    mostrar_marcadores_classe: bool = False   # False -> all circles 'o'
    mostrar_elipses_grupo:     bool = False   # False -> no T2/convex hull ellipse

    # ---- Figure detail level ----
    # False (default): gera apenas o conjunto ESSENCIAL de figuras (scores PCA/
    #   PLS-DA, confusao, ROC/AUC, selecao de LVs, SR+VIP, outliers T2/Q, e a
    #   aceitacao DD-SIMCA quando aplicavel). Mais rapido e menos arquivos.
    # True: gera tambem as figuras EXPLORATORIAS/detalhadas (HCA, loadings PCA,
    #   pre-processamento, contribuicao de score, DD-SIMCA por classe, Cooman).
    figuras_detalhadas: bool = False

    # ---- Group-aware validation (Q1 differentiator) ----
    # When True and mae_id is available, uses GroupKFold/GroupShuffleSplit
    # so that T1/T2/T3 of the same physical point stay in the same fold/holdout.
    agrupar_por_mae_id: bool = True

    # ---- Spectral truncation (useful FT-NIR range: 4000-10000 cm-1) -------
    # Removes FFT edge noise (0/8/16/24 cm-1 appear as false top
    # VIP when the SG derivative amplifies that region). Applied BEFORE
    # any preprocessing.
    wn_min: float = 4000.0
    wn_max: float = 10000.0

    # ---- Preprocessing ---------------------------------------------------
    # Quick preset. When != 'custom', overrides individual flags.
    #   'msc_sg_mc'   : MSC -> SG -> mean-centering (BEST: 0.923 bal.acc full)
    #   'snv_sg_mc'   : SNV -> SG -> mean-centering (Rinnan et al.)
    #   'autoscaling' : StandardScaler only (good on subset, poor on full: 0.472)
    #   'mc'          : mean-centering only
    #   'custom'      : honors aplicar_snv / aplicar_sg / aplicar_mc below
    preprocessamento_padrao: str = "msc_sg_mc"   # v14: best on full dataset (1807)

    aplicar_snv: bool = True
    aplicar_sg: bool = True
    sg_window: int = 25
    sg_polyorder: int = 2
    sg_deriv: int = 1
    aplicar_mc: bool = True

    max_lvs: int = 40
    n_pcs_pca: int = 10
    # HCA: dendrogram uses PCA scores with hca_n_pcs components
    # (reduces spectral noise before clustering). comparar_hca_pipelines
    # generates a dendrogram panel per preprocessing method.
    hca_n_pcs: int = 65
    # Extra opt-in (fora do conjunto padrao de ~7 figuras "core"; ligar na mao).
    comparar_hca_pipelines: bool = False
    n_splits_cv: int = 5
    n_repeats_cv: int = 3

    frac_cal: float = 0.70
    # Metodo de split calibracao/validacao da regressao PLS (N2/N3):
    # 'aleatoria' (default, comportamento historico -- GroupShuffleSplit
    # group-aware por mae_id, ou permutacao simples sem mae_id) |
    # 'kennard_stone' (Kennard & Stone 1969 -- cobertura maximamente
    # representativa do espaco espectral em vez de aleatoria; group-aware,
    # colapsa replicas fisicas num espectro medio por grupo antes de
    # selecionar). Hiperparametro avancado, config-only (mesmo precedente
    # de ipls_n_intervalos/vip_threshold_sel/etc -- nao exposto no app/CLI).
    divisao_cal_val: str = "aleatoria"   # 'aleatoria' | 'kennard_stone'

    n_permutacoes: int = 200
    n_permutacoes_wold: int = 200        # 200 for publication; 50 is minimum for diagnostic
    n_bootstrap_vip: int = 30
    n_bootstrap_bca: int = 500
    # Os 3 abaixo sao "extra" opt-in (fora do conjunto padrao de ~7 figuras
    # "core"): validacoes/comparacoes adicionais, uteis mas nao essenciais
    # para o resultado principal. Ligar na mao quando quiser mais rigor.
    comparar_pipelines: bool = False
    executar_wold: bool = False
    executar_cv_anova: bool = False
    # Teste de incerteza de Martens (Martens & Martens 2000): jackknifing
    # group-aware dos coeficientes PLS -- teste de hipotese formal (p-valor)
    # de significancia por variavel, mais rigoroso que VIP/SR (magnitude).
    executar_martens: bool = False
    # Paralelismo (processos, via joblib/loky) para os testes de permutacao/
    # Wold — cada iteracao e independente (mesma X, so o rotulo e
    # reembaralhado), entao rodar em paralelo NAO altera nenhum resultado
    # numerico, so o tempo de execucao (verificado por teste de regressao).
    # Padrao 1 (sequencial) preserva o comportamento atual sem mudanca.
    # Medido: n_jobs=4 ~2x mais rapido no pipeline completo (threading NAO
    # ajuda aqui — overhead do sklearn e Python/GIL-bound; processos sim).
    # Em ambientes com pouca RAM/CPU (ex.: Streamlit Cloud gratuito), deixe em 1
    # (processos extras multiplicam o uso de memoria).
    n_jobs_permutacao: int = 1

    frac_holdout: float = 0.20         # v14: external holdout by default
    # v15: pure samples (conc==0) ALWAYS stay in training — they are scarce (3/class)
    # and precious for DD-SIMCA/interpretation. Only adulterated go to holdout.
    holdout_preserva_puros: bool = True
    seed_holdout: int = 42

    n_por_classe: int = 20
    n_pontos_sint: int = 1000
    n_replicas_sint: int = 3   # replicas fisicas/ponto (estilo T1/T2/T3) no modo sintetico
    # Modo sintetico: adulterantes a gerar por especie (letras A/M/S). Vazio =
    # so o gradiente puro legado (nao muda dados de teste existentes). Quando
    # preenchido, cada especie ganha puros + esses adulterantes em varios teores
    # -> permite exercitar o heatmap especie x adulterante (N3) sinteticamente.
    sint_adulterantes: Tuple[str, ...] = ()

    seed: int = 42

    # Sprint 3
    # DD-SIMCA e' o "core" automatico de N2 (executar() forca True quando
    # nivel=="N2", e ignora o toggle quando nivel=="N1" -- ver executar()).
    # Default False aqui so' afeta N3, onde vira extra opt-in de verdade.
    executar_ddsimca: bool = False
    ddsimca_n_components: int = 7       # PCA LVs per DD-SIMCA model (3 was insufficient — UCL poorly calibrated)
    ddsimca_ucl_method: str = "empirical"  # 'empirical' | 'theoretical' | 'chi2'
    # v14: 'todos' trains each model with ALL samples of the class
    # (exploratory; works with few pure samples). 'puros' = true one-class N2
    # but requires >=15 pure/class (current data: 3/class).
    ddsimca_treinar_em: str = "puros"   # 'todos' | 'puros'
    # Extra opt-in (fora do conjunto padrao de ~7 figuras "core").
    executar_opls: bool = False
    n_ortho_opls: int = 1               # OPLS-DA orthogonal components
    executar_benchmark: bool = False    # v27: SVM / RF / XGBoost vs PLS-DA (same CV)
    # Auto-Benchmark de REGRESSAO (N2/N3): Ridge/Lasso/Elastic Net/SVR/RF vs
    # PLS-R, por especie, mesmo split cal/val e pre-processamento (ver
    # avaliacao_modelos.benchmark_regressao_por_especie). So' roda quando
    # ha regressao multi-especie (mesma condicao de pls_regressao_por_especie).
    executar_benchmark_regressao: bool = False
    executar_monte_carlo: bool = False      # v28: MC CV (N × GroupShuffleSplit) for 95% CI
    n_monte_carlo: int = 100               # number of MC repetitions
    monte_carlo_test_size: float = 0.25    # test fraction per MC repetition
    monte_carlo_incluir_todos: bool = False # v28: run all benchmark models in MC CV
    executar_shap: bool = False            # v28: SHAP values (TreeExplainer) for ensemble
    shap_max_amostras: int = 500        # sample limit for SHAP (memory control)

    # ---- Class exclusion (e.g. Copaiba with anomalous batch) ----
    excluir_classes: Tuple[str, ...] = ()

    # ---- STAGE 4: Variable selection ----
    # Extra opt-in (fora do conjunto padrao de ~7 figuras "core").
    executar_etapa4: bool = False
    ipls_n_intervalos: int = 20         # iPLS: number of intervals
    vip_threshold_sel: float = 1.0      # selection by VIP >= threshold
    sr_top_frac: float = 0.20           # selection by SR: top fraction
    splsda_keep_por_comp: int = 50      # sPLS-DA: non-zero variables/component
    # SPA/APS (Successive Projections Algorithm, Araujo et al. 2001) and
    # AG (Genetic Algorithm, GA-PLS) — opt-in (default False) because they
    # run many more CV evaluations than iPLS/VIP/SR/sPLS-DA (heavier, like
    # executar_benchmark/executar_shap).
    executar_spa: bool = False
    spa_n_vars_max: int = 20            # SPA: max chain length (variables)
    spa_n_starts: int = 25              # SPA: starting variables sampled (evenly across spectrum)
    executar_ag: bool = False
    ag_tam_populacao: int = 20          # AG: chromosomes per generation
    ag_n_geracoes: int = 15             # AG: number of generations
    ag_prob_mutacao: float = 0.02       # AG: per-bit mutation probability
    ag_frac_inicial: float = 0.10       # AG: initial fraction of variables "on" per chromosome
