"""app_tabs/predicao.py — Aba 6 (Prediction): aplica um modelo `.joblib`
salvo a amostras novas. Extraído de app_quimiometria.py (item 18).
"""
from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Callable, Dict, List

import pandas as pd
import streamlit as st

from guaraci.predicao import (
    predizer_amostras as _predizer,
    validar_pacote_modelo as _validar_pacote_modelo,
    carregar_csv_predicao as _carregar_csv_predicao,
)


def render(upload_bloqueado: bool, tok: Callable[[], Dict[str, str]]) -> None:
    """Renderiza a aba Prediction.

    `upload_bloqueado` reflete GUARACI_DISABLE_MODEL_UPLOAD (mitigação de RCE
    via pickle em deploy público — ver comentário em app_quimiometria.py).
    """
    st.subheader("Prediction on Unknown Samples")
    st.markdown(
        "Upload a `.joblib` model generated by the pipeline and a CSV "
        "with new spectra (columns = wavenumbers, no class column)."
    )

    col_m1, col_m2 = st.columns(2)
    with col_m1:
        st.markdown("**1. Trained model (.joblib)**")
        if upload_bloqueado:
            upld_jbl = None
            st.info(
                "🔒 Model upload is disabled on this public deployment "
                "(a `.joblib`/pickle can execute arbitrary code when loaded). "
                "Provide a local path to a model file below instead.")
        else:
            st.caption(
                "⚠️ Only upload `.joblib` models you generated yourself. "
                "A model file is a pickle and **runs code when loaded** — "
                "never load one from an untrusted source.")
            upld_jbl = st.file_uploader("Upload the .joblib model",
                                        type=["joblib", "pkl"],
                                        key="pred_model_upload")
        cam_jbl  = st.text_input("Or local path to model",
                                  key="pred_model_path",
                                  placeholder="C:/results/model_pls.joblib")

    with col_m2:
        st.markdown("**2. New spectra (CSV)**")
        upld_csv_pred = st.file_uploader("Upload CSV with new spectra",
                                          type=["csv", "txt"],
                                          key="pred_csv_upload")
        cam_csv_pred  = st.text_input("Or local path to CSV",
                                       key="pred_csv_path",
                                       placeholder="C:/data/new_spectra.csv")
        st.text_input(
            "First column to use as wavenumber (leave empty = auto)",
            key="pred_col_wn",
            placeholder="e.g.: 4000.0  (name or index of first spectral column)")

    # ---- Predict button -------------------------------------------------
    st.divider()
    if st.button("🔮 Predict", type="primary", key="btn_predizer",
                 use_container_width=True):
        erros_pred: List[str] = []
        pkg_pred = None

        # Load model
        try:
            import joblib
            if upld_jbl is not None and not upload_bloqueado:
                tmp_jbl = Path(tempfile.gettempdir()) / "pq_pred_model.joblib"
                with open(tmp_jbl, "wb") as f:
                    f.write(upld_jbl.getvalue())
                pkg_pred = joblib.load(str(tmp_jbl))
            elif cam_jbl and os.path.exists(cam_jbl):
                pkg_pred = joblib.load(cam_jbl)
            # NOTE: this is STRUCTURE validation only — it runs AFTER joblib.load,
            # so it does NOT prevent RCE from a malicious pickle (the code already
            # ran during load). The real mitigation is upstream: only trusted
            # sources reach here (upload gated by upload_bloqueado on
            # public deployments; local paths are operator-controlled).
            if pkg_pred is not None:
                _validar_pacote_modelo(pkg_pred)
            else:
                erros_pred.append("No valid model provided (upload or path).")
        except Exception as e_jbl:
            erros_pred.append(f"Error loading model: {e_jbl}")

        # Load prediction CSV
        X_pred_raw = None
        wn_pred    = None
        try:
            fonte_csv = (upld_csv_pred if upld_csv_pred is not None
                         else cam_csv_pred if cam_csv_pred and os.path.exists(cam_csv_pred)
                         else None)
            if fonte_csv is None:
                erros_pred.append("No spectra CSV provided.")
            else:
                X_pred_raw, wn_pred, meta_pred = _carregar_csv_predicao(fonte_csv)
                st.session_state["pred_amostras"] = meta_pred
        except Exception as e_csv:
            erros_pred.append(f"Error reading CSV: {e_csv}")

        if erros_pred:
            for e in erros_pred:
                st.error(e)
        elif pkg_pred is not None and X_pred_raw is not None:
            try:
                with st.spinner("Applying model..."):
                    df_res = _predizer(pkg_pred, X_pred_raw, wn_pred)
                    # Re-attach metadata (sample names) if available
                    meta_df = st.session_state.get("pred_amostras")
                    if meta_df is not None and len(meta_df) == len(df_res):
                        df_res = pd.concat(
                            [meta_df.reset_index(drop=True), df_res], axis=1)
                st.session_state["pred_resultados"] = df_res
                st.success(f"Prediction complete: {len(df_res)} samples.")
            except Exception as e_pred:
                st.error(f"Prediction error: {e_pred}")

    # ---- Results display ----------------------------------------
    df_show = st.session_state.get("pred_resultados")
    if df_show is not None:
        st.divider()
        st.markdown("**Prediction results**")

        # Color accepted/rejected — via design tokens (contraste correto em
        # tema claro e escuro).
        _tkp = tok()
        def _colorir_aceito(val):
            if val is True:
                return (f"background-color:{_tkp['success_bg']};"
                        f" color:{_tkp['success']}")
            if val is False:
                return (f"background-color:{_tkp['error_bg']};"
                        f" color:{_tkp['error']}")
            return ""

        cols_bool_colorir = [c for c in ("aceito", "AD_dentro_dominio")
                             if c in df_show.columns]
        if cols_bool_colorir:
            st.dataframe(
                df_show.style.map(_colorir_aceito, subset=cols_bool_colorir),
                use_container_width=True,
            )
        else:
            st.dataframe(df_show, use_container_width=True)

        # Download CSV
        csv_bytes = df_show.to_csv(index=False, sep=";", decimal=",").encode("utf-8")
        st.download_button(
            "⬇️ Download results (.csv)",
            data=csv_bytes,
            file_name="predicao_resultados.csv",
            mime="text/csv",
            use_container_width=True,
        )

        # Quick summary
        col_m1, col_m2 = st.columns(2)
        if "aceito" in df_show.columns:
            n_ac = int(df_show["aceito"].sum())
            n_tot = len(df_show)
            with col_m1:
                st.metric("Accepted samples (PLS-DA fit, T² ≤ UCL and Q ≤ UCL)",
                          f"{n_ac} / {n_tot}",
                          delta=f"{n_ac/n_tot*100:.1f}%")
        # Applicability Domain (PCA-based, Jaworska et al. 2005) — only
        # present if the .joblib package carries the AD artifacts (pipeline
        # versions exporting pca/ad_var_t/ad_t2_limite/ad_q_limite).
        if "AD_dentro_dominio" in df_show.columns:
            n_ad = int(df_show["AD_dentro_dominio"].sum())
            n_tot = len(df_show)
            with col_m2:
                st.metric("Within applicability domain (PCA T²/Q)",
                          f"{n_ad} / {n_tot}",
                          delta=f"{n_ad/n_tot*100:.1f}%")
