"""app_tabs/predicao.py — Aba 6 (Prediction): aplica um modelo `.joblib`
salvo a amostras novas. Extraído de app_quimiometria.py (item 18).
"""
from __future__ import annotations

import os
from typing import Callable, Dict, List

import pandas as pd
import streamlit as st

from guaraci.predicao import (
    predict_samples as _predizer,
    predict_blind as _predizer_cego,
    validate_model_package as _validar_pacote_modelo,
    load_prediction_csv as _carregar_csv_predicao,
)
from guaraci.app_logic import temp_upload_path


def render(upload_bloqueado: bool, tok: Callable[[], Dict[str, str]],
           T: Callable[[str], str] = lambda s: s) -> None:
    """Renderiza a aba Prediction.

    `upload_bloqueado` reflete GUARACI_DISABLE_MODEL_UPLOAD (mitigação de RCE
    via pickle em deploy público — ver comentário em app_quimiometria.py).
    Também esconde o campo de caminho local do CSV de predição quando ativo
    (achado S-NOVO-1 da auditoria de segurança de 2026-09-01): um campo de
    texto livre com caminho de servidor, num app público sem autenticação,
    deixa qualquer visitante ler qualquer arquivo de texto acessível ao
    processo, não só o operador que "sabe o caminho certo".

    `T`: traducao PT/EN (mesma funcao `_T` de app_quimiometria.py). Default
    no-op so' para chamada direta em teste isolado.
    """
    st.subheader(T("Prediction on Unknown Samples"))
    st.markdown(T(
        "Upload a `.joblib` model generated by the pipeline and a CSV "
        "with new spectra (columns = wavenumbers, no class column)."
    ))

    col_m1, col_m2 = st.columns(2)
    with col_m1:
        st.markdown(T("**1. Trained model (.joblib)**"))
        if upload_bloqueado:
            # CORRIGIDO em 2026-08-07 (achado S1 da auditoria de
            # seguranca -- ver AUDITORIA_SEGURANCA_
            # 2026-08-07.md): o campo "local path" ficava disponivel MESMO
            # com o upload bloqueado, e um visitante remoto podia digitar
            # QUALQUER caminho do servidor ali. Um campo de texto num app
            # web publico NUNCA e' "so' o operador digita" -- qualquer
            # visitante alcanca. Por isso o campo de caminho local tambem
            # fica oculto neste mode, nao so' o uploader.
            upld_jbl = None
            cam_jbl = ""
            confia_modelo = False
            st.info(T(
                "🔒 Model loading (upload and local path) is disabled on "
                "this public deployment — a `.joblib`/pickle can execute "
                "arbitrary code when loaded, from ANY path on the server, "
                "not just uploaded files. Run the CLI or app locally to "
                "use the Prediction tab."))
        else:
            st.caption(T(
                "⚠️ Only upload `.joblib` models you generated yourself. "
                "A model file is a pickle and **runs code when loaded** — "
                "never load one from an untrusted source."))
            upld_jbl = st.file_uploader(T("Upload the .joblib model"),
                                        type=["joblib", "pkl"],
                                        key="pred_model_upload")
            cam_jbl  = st.text_input(T("Or local path to model"),
                                      key="pred_model_path",
                                      placeholder="C:/results/model_pls.joblib")
            confia_modelo = st.checkbox(
                T("I trust the source of this model file (required to load "
                "it — `.joblib` executes code when loaded, see "
                "docs/SECURITY.md)"),
                key="pred_model_confia", value=False)

    with col_m2:
        st.markdown(T("**2. New spectra (CSV)**"))
        upld_csv_pred = st.file_uploader(T("Upload CSV with new spectra"),
                                          type=["csv", "txt"],
                                          key="pred_csv_upload")
        if upload_bloqueado:
            cam_csv_pred = ""
            st.caption(T(
                "🔒 Local path to CSV is disabled on this public "
                "deployment — a free-text server-side path would let any "
                "visitor read arbitrary files on the server. Use the "
                "upload above instead."))
        else:
            cam_csv_pred = st.text_input(T("Or local path to CSV"),
                                          key="pred_csv_path",
                                          placeholder="C:/data/new_spectra.csv")
        st.text_input(
            T("First column to use as wavenumber (leave empty = auto)"),
            key="pred_col_wn",
            placeholder="e.g.: 4000.0  (name or index of first spectral column)")

    # ---- Predict button -------------------------------------------------
    st.divider()
    if st.button(T("🔮 Predict"), type="primary", key="btn_predizer",
                 use_container_width=True):
        erros_pred: List[str] = []
        pkg_pred = None

        # Load model
        try:
            from guaraci.predicao import load_model as _load_model
            if not confia_modelo:
                erros_pred.append(T(
                    "Check 'I trust the source of this model file' above "
                    "before loading — required (see docs/SECURITY.md)."))
            elif upld_jbl is not None and not upload_bloqueado:
                # Isolado por sessao (achado de auditoria de seguranca,
                # 2026-08-07 -- ver docstring de app_logic.temp_upload_path):
                # um caminho fixo/previsivel numa pasta temp compartilhada
                # permite que 2 sessoes concorrentes (deploy multi-usuario)
                # se pisem -- a sessao B sobrescreve o arquivo entre a
                # sessao A escrever e carregar, e A acaba executando o
                # pickle de B sem saber.
                import uuid
                if "_upload_session_id" not in st.session_state:
                    st.session_state["_upload_session_id"] = uuid.uuid4().hex
                tmp_jbl = temp_upload_path(
                    "pq_pred_model.joblib", st.session_state["_upload_session_id"])
                tmp_jbl.parent.mkdir(parents=True, exist_ok=True)
                with open(tmp_jbl, "wb") as f:
                    f.write(upld_jbl.getvalue())
                pkg_pred = _load_model(str(tmp_jbl), confiar=True)
            elif cam_jbl and os.path.exists(cam_jbl):
                pkg_pred = _load_model(cam_jbl, confiar=True)
            # NOTE: this is STRUCTURE validation only — it runs AFTER the model
            # is loaded, so it does NOT prevent RCE from a malicious pickle
            # (the code already ran during load). The real mitigation is the
            # confia_modelo checkbox above (explicit human confirmation) plus
            # the sha256 manifest check inside load_model, which DOES
            # run before joblib.load when a manifest is present.
            if pkg_pred is not None:
                _validar_pacote_modelo(pkg_pred)
            elif not erros_pred:
                erros_pred.append(T("No valid model provided (upload or path)."))
        except Exception as e_jbl:  # noqa: BLE001 -- multi-etapa (joblib.load
            # + validacao de estrutura do pacote); erro exibido ao usuario
            # via erros_pred/st.error abaixo.
            erros_pred.append(T("Error loading model: {e}").format(e=e_jbl))

        # Load prediction CSV
        X_pred_raw = None
        wn_pred    = None
        try:
            fonte_csv = (upld_csv_pred if upld_csv_pred is not None
                         else cam_csv_pred if cam_csv_pred and os.path.exists(cam_csv_pred)
                         else None)
            if fonte_csv is None:
                erros_pred.append(T("No spectra CSV provided."))
            else:
                X_pred_raw, wn_pred, meta_pred = _carregar_csv_predicao(fonte_csv)
                st.session_state["pred_amostras"] = meta_pred
        except Exception as e_csv:  # noqa: BLE001 -- parsing defensivo de
            # CSV de amostra nova (formato variavel); erro exibido ao usuario.
            erros_pred.append(T("Error reading CSV: {e}").format(e=e_csv))

        if erros_pred:
            for e in erros_pred:
                st.error(e)
        elif pkg_pred is not None and X_pred_raw is not None:
            try:
                with st.spinner(T("Applying model...")):
                    # Bloco 9b (D6, portado do CLI nesta rodada -- ver
                    # guaraci.py:_menu_prediction, mesma logica, zero
                    # duplicacao de calculo): quando o pacote traz o
                    # ensemble de identificacao, roda o fluxo completo
                    # Detectar->Identificar->Quantificar em vez do fluxo
                    # simples N1. Modelos exportados antes do Bloco 9b nao
                    # tem essa chave -- cai no caminho anterior, sem quebrar.
                    resultados_cego = None
                    if pkg_pred.get("identification_ensemble"):
                        df_res, resultados_cego = _predizer_cego(
                            pkg_pred, X_pred_raw, wn_pred)
                        df_res["detectado_puro_especie"] = [
                            r.pureza.aceito for r in resultados_cego]
                        df_res["pureza_confiavel"] = [
                            r.pureza.confiavel for r in resultados_cego]
                        df_res["classe_identificada"] = [
                            r.identificacao.classe_identificada for r in resultados_cego]
                        df_res["identificacao_cobertura"] = [
                            (r.identificacao.cobertura_status.value
                             if r.identificacao.cobertura_status else None)
                            for r in resultados_cego]
                        df_res["identificacao_alpha_alcancavel"] = [
                            r.identificacao.alpha_alcancavel for r in resultados_cego]
                        df_res["identificacao_candidatos"] = [
                            ", ".join(r.identificacao.candidatos_ambiguos)
                            for r in resultados_cego]
                        df_res["teor_estimado"] = [
                            r.quantificacao.teor_estimado for r in resultados_cego]
                        df_res["quantificacao_motivo_bloqueio"] = [
                            r.quantificacao.motivo_bloqueio for r in resultados_cego]
                        df_res["alpha_total"] = [
                            r.alpha_total for r in resultados_cego]
                    else:
                        df_res = _predizer(pkg_pred, X_pred_raw, wn_pred)
                    # Re-attach metadata (sample names) if available
                    meta_df = st.session_state.get("pred_amostras")
                    if meta_df is not None and len(meta_df) == len(df_res):
                        df_res = pd.concat(
                            [meta_df.reset_index(drop=True), df_res], axis=1)
                st.session_state["pred_resultados"] = df_res
                st.session_state["pred_resultados_cego"] = resultados_cego
                st.success(T("Prediction complete: {n} samples.").format(n=len(df_res)))
            except Exception as e_pred:  # noqa: BLE001 -- multi-etapa
                # (predizer + concat de metadados); erro exibido ao usuario.
                st.error(T("Prediction error: {e}").format(e=e_pred))

    # ---- Results display ----------------------------------------
    df_show = st.session_state.get("pred_resultados")
    if df_show is not None:
        st.divider()
        st.markdown(T("**Prediction results**"))

        # Color accepted/rejected — via design tokens (contraste correto em
        # tema claro e escuro).
        _tkp = tok()
        def _colorir_aceito(val):
            if val is True:
                return (f"background-color:{_tkp['success_bg']};"
                        f" color:{_tkp['success']}")
            if val is False:
                return (f"background-color:{_tkp['error_bg']};"
                        f" color:{_tkp['error']}")
            return ""

        cols_bool_colorir = [c for c in ("aceito", "AD_dentro_dominio")
                             if c in df_show.columns]
        if cols_bool_colorir:
            st.dataframe(
                df_show.style.map(_colorir_aceito, subset=cols_bool_colorir),
                use_container_width=True,
            )
        else:
            st.dataframe(df_show, use_container_width=True)

        # Download CSV
        csv_bytes = df_show.to_csv(index=False, sep=";", decimal=",").encode("utf-8")
        st.download_button(
            T("⬇️ Download results (.csv)"),
            data=csv_bytes,
            file_name="predicao_resultados.csv",
            mime="text/csv",
            use_container_width=True,
        )

        # Quick summary
        col_m1, col_m2 = st.columns(2)
        if "aceito" in df_show.columns:
            n_ac = int(df_show["aceito"].sum())
            n_tot = len(df_show)
            with col_m1:
                st.metric(T("Within PLS-DA model fit"), f"{n_ac} / {n_tot}",
                          delta=f"{n_ac/n_tot*100:.1f}%")
                st.caption(T(
                    "Hotelling T² (distance along the model's main "
                    "directions) and Q-residual (unexplained variation) "
                    "both within their statistical limit — see the "
                    "'criterio' column for the exact rule applied. A "
                    "sample outside this fit is an atypical spectrum for "
                    "the calibration, not necessarily 'adulterated'."))
        # Applicability Domain (PCA-based, Jaworska et al. 2005) — only
        # present if the .joblib package carries the AD artifacts (pipeline
        # versions exporting pca/ad_var_t/ad_t2_limite/ad_q_limite).
        if "AD_dentro_dominio" in df_show.columns:
            n_ad = int(df_show["AD_dentro_dominio"].sum())
            n_tot = len(df_show)
            with col_m2:
                st.metric(T("Within applicability domain"), f"{n_ad} / {n_tot}",
                          delta=f"{n_ad/n_tot*100:.1f}%")
                st.caption(T(
                    "Exploratory PCA check (Hotelling T²/Q-residual, "
                    "Jaworska et al. 2005) of similarity to the training "
                    "set as a whole — a broader, less strict screen than "
                    "the PLS-DA fit above. 'Outside' flags a spectrum "
                    "unlike anything the model was calibrated on."))

        # Bloco 9b -- Fluxo cego (Detectar->Identificar->Quantificar).
        # Mesmos numeros/regras do resumo do CLI (_menu_prediction), so'
        # apresentado como metricas Streamlit em vez de texto Rich.
        resultados_cego = st.session_state.get("pred_resultados_cego")
        if "classe_identificada" in df_show.columns and resultados_cego:
            st.divider()
            st.markdown(T("**Blind flow — Detect → Identify → Quantify**"))
            n_tot = len(df_show)
            n_pura = sum(1 for r in resultados_cego if r.pureza.aceito is True)
            n_adulterada = sum(1 for r in resultados_cego if r.pureza.aceito is False)
            n_identificado = sum(
                1 for r in resultados_cego
                if r.identificacao.classe_identificada is not None)
            n_quantificado = sum(
                1 for r in resultados_cego
                if r.quantificacao.teor_estimado is not None)

            col_c1, col_c2, col_c3 = st.columns(3)
            with col_c1:
                st.metric(T("🧪 Purity (predicted species)"),
                          f"{n_pura} / {n_tot}",
                          delta=T("pure"))
                st.caption(T(
                    "DD-SIMCA for the species predicted above. "
                    "{n} detected as adulterated.").format(n=n_adulterada))
            with col_c2:
                st.metric(T("🏷 Adulterant identified"),
                          f"{n_identificado} / {n_tot}")
                st.caption(T(
                    "UNKNOWN means no species×adulterant combination had a "
                    "statistical guarantee both sufficient AND exclusive "
                    "for this sample — either no guarantee, or 2+ "
                    "validated combinations tied (also blocks the label)."))
            with col_c3:
                st.metric(T("⚖ Quantified"), f"{n_quantificado} / {n_tot}")
                st.caption(T(
                    "Blocked = quantification refused because the "
                    "adulterant was not reliably identified — see "
                    "'quantificacao_motivo_bloqueio' in the table above."))
            st.warning(T(
                "⚠ 'classe_identificada' only ever exists when "
                "'identificacao_cobertura'='validado' (formal statistical "
                "guarantee, calibrated with ≥2 independent collection "
                "sessions) — there is no 'informational' label without "
                "that guarantee. 'identificacao_candidatos' carries only "
                "the closest guess (with NO guarantee at all) for "
                "reference, never as a result to act on for a quality "
                "decision without confirming by a reference method."))
